# Generated by Django 5.0.1 on 2025-08-12 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molecules', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('receptor_file', models.FileField(blank=True, null=True, upload_to='receptors/')),
                ('ligand_file', models.FileField(blank=True, null=True, upload_to='ligands/')),
                ('exhaustiveness', models.IntegerField(default=8)),
                ('num_modes', models.IntegerField(default=9)),
                ('energy_range', models.FloatField(default=3.0)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_jobs', to='projects.batch')),
            ],
            options={
                'db_table': 'screening_jobs',
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docking_score', models.FloatField()),
                ('rmsd', models.FloatField(blank=True, null=True)),
                ('binding_pose', models.JSONField(default=dict)),
                ('is_hit', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.screeningjob')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molecules.molecule')),
            ],
            options={
                'db_table': 'screening_results',
                'ordering': ['docking_score'],
            },
        ),
    ]
