# Generated by Django 5.0.1 on 2025-08-12 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smiles', models.TextField()),
                ('canonical_smiles', models.TextField(blank=True)),
                ('inchi', models.TextField(blank=True)),
                ('inchi_key', models.CharField(blank=True, max_length=27, null=True, unique=True)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('logp', models.FloatField(blank=True, null=True)),
                ('hbd', models.IntegerField(blank=True, null=True)),
                ('hba', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'molecules',
            },
        ),
    ]
