# Generated by Django 5.0.1 on 2025-08-12 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uniprot_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pdb_id', models.CharField(blank=True, max_length=10)),
                ('sequence', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'targets',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('therapeutic_area', models.CharField(blank=True, max_length=100)),
                ('target_indication', models.CharField(blank=True, max_length=255)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('center_x', models.FloatField(blank=True, null=True)),
                ('center_y', models.FloatField(blank=True, null=True)),
                ('center_z', models.FloatField(blank=True, null=True)),
                ('size_x', models.FloatField(default=20.0)),
                ('size_y', models.FloatField(default=20.0)),
                ('size_z', models.FloatField(default=20.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='projects.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.target')),
            ],
            options={
                'db_table': 'batches',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
