# Generated by Django 5.1 on 2024-12-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_discovery', '0002_dataset_scaffold_remove_compound_ligand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='target_type',
        ),
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default='Default Target', max_length=200),
        ),
        migrations.AddField(
            model_name='target',
            name='pdb_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
