version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: omnidrug
      POSTGRES_USER: omnidrug_user
      POSTGRES_PASSWORD: omnidrug_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    command: celery -A omnidrug worker -l info
    volumes:
      - ../backend:/app
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  
  flower:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    command: celery -A omnidrug flower
    volumes:
      - ../backend:/app
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - celery

volumes:
  postgres_data: